version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore AWSCodePipelineDemo/WaltersRanch.csproj
  build:
    commands:
      - dotnet build AWSCodePipelineDemo/WaltersRanch.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ WaltersRanch/WaltersRanch.csproj
artifacts:
  files:
    - '**/*'